name = "ktor-native"
version = "0.1.0"

[kotlin]
version = "2.3.20"

[kotlin.plugins]
serialization = true

[build]
target = "linuxX64"
main = "main"
sources = ["src"]

[dependencies]
"io.ktor:ktor-server-core" = "3.4.3"
"io.ktor:ktor-server-cio" = "3.4.3"
"io.ktor:ktor-server-content-negotiation" = "3.4.3"
"io.ktor:ktor-serialization-kotlinx-json" = "3.4.3"
"org.jetbrains.kotlinx:kotlinx-serialization-json" = "1.11.0"
